//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dangl.BCF.APIObjects.V21
{
    using System;
    
    public class Bitmap_POST
    {
        
        private string _bitmap_data;
        
        private Location _location;
        
        private Direction _normal;
        
        private Direction _up;
        
        private float _height;

        public Bitmap_type Bitmap_type { get; set; }

        public virtual string Bitmap_data
        {
            get
            {
                return _bitmap_data;
            }
            set
            {
                _bitmap_data = value;
            }
        }
        
        public virtual Location Location
        {
            get
            {
                return _location;
            }
            set
            {
                _location = value;
            }
        }
        
        public virtual Direction Normal
        {
            get
            {
                return _normal;
            }
            set
            {
                _normal = value;
            }
        }
        
        public virtual Direction Up
        {
            get
            {
                return _up;
            }
            set
            {
                _up = value;
            }
        }
        
        public virtual float Height
        {
            get
            {
                return _height;
            }
            set
            {
                _height = value;
            }
        }
    }
}
