//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Dangl.BCF.APIObjects.V21
{
    // Schema for coloring GET, BCF REST API.
    public class Coloring_GET
    {
        
        private List<Coloring> _coloring;
        
        public virtual List<Coloring> Coloring
        {
            get
            {
                return _coloring;
            }
            set
            {
                _coloring = value;
            }
        }
    }
}
