//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Dangl.BCF.APIObjects.V21
{
    public class Coloring
    {
        
        private string _color;
        
        private List<Component> _components;
        
        public virtual string Color
        {
            get
            {
                return _color;
            }
            set
            {
                _color = value;
            }
        }
        
        public virtual List<Component> Components
        {
            get
            {
                return _components;
            }
            set
            {
                _components = value;
            }
        }
    }
}
