//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Dangl.BCF.APIObjects.V21
{
    public class Components
    {
        
        private List<Component> _selection;
        
        private List<Coloring> _coloring;
        
        private Visibility _visibility;
        
        public virtual List<Component> Selection
        {
            get
            {
                return _selection;
            }
            set
            {
                _selection = value;
            }
        }
        
        public virtual List<Coloring> Coloring
        {
            get
            {
                return _coloring;
            }
            set
            {
                _coloring = value;
            }
        }
        
        public virtual Visibility Visibility
        {
            get
            {
                return _visibility;
            }
            set
            {
                _visibility = value;
            }
        }
    }
}
