//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Dangl.BCF.APIObjects.V21
{
    // Dynamic Client Meta Data
    public class Dyn_reg_client_POST
    {
        
        private string _client_name;
        
        private string _client_description;
        
        private string _client_url;
        
        private string _redirect_url;
        
        [Required()]
        [StringLength(60)]
        public virtual string Client_name
        {
            get
            {
                return _client_name;
            }
            set
            {
                _client_name = value;
            }
        }
        
        [StringLength(4000)]
        public virtual string Client_description
        {
            get
            {
                return _client_description;
            }
            set
            {
                _client_description = value;
            }
        }
        
        public virtual string Client_url
        {
            get
            {
                return _client_url;
            }
            set
            {
                _client_url = value;
            }
        }
        
        [Required()]
        public virtual string Redirect_url
        {
            get
            {
                return _redirect_url;
            }
            set
            {
                _redirect_url = value;
            }
        }
    }
}
