//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Dangl.BCF.APIObjects.V21
{
    // Schema for a single file GET, BCF REST API.
    public class File_GET
    {
        
        private string _ifc_project;
        
        private string _ifc_spatial_structure_element;
        
        private string _file_name;
        
        private DateTime _date;
        
        private string _reference;
        
        public virtual string Ifc_project
        {
            get
            {
                return _ifc_project;
            }
            set
            {
                _ifc_project = value;
            }
        }
        
        public virtual string Ifc_spatial_structure_element
        {
            get
            {
                return _ifc_spatial_structure_element;
            }
            set
            {
                _ifc_spatial_structure_element = value;
            }
        }
        
        public virtual string File_name
        {
            get
            {
                return _file_name;
            }
            set
            {
                _file_name = value;
            }
        }
        
        public virtual DateTime Date
        {
            get
            {
                return _date;
            }
            set
            {
                _date = value;
            }
        }
        
        public virtual string Reference
        {
            get
            {
                return _reference;
            }
            set
            {
                _reference = value;
            }
        }
    }
}
