//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dangl.BCF.APIObjects.V21
{
    public class Line
    {
        
        private Point _start_point;
        
        private Point _end_point;
        
        public virtual Point Start_point
        {
            get
            {
                return _start_point;
            }
            set
            {
                _start_point = value;
            }
        }
        
        public virtual Point End_point
        {
            get
            {
                return _end_point;
            }
            set
            {
                _end_point = value;
            }
        }
    }
}
