//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Dangl.BCF.APIObjects.V21
{
    // Schema for selection GET, BCF REST API.
    public class Selection_GET
    {
        
        private List<Component> _selection;
        
        public virtual List<Component> Selection
        {
            get
            {
                return _selection;
            }
            set
            {
                _selection = value;
            }
        }
    }
}
