//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dangl.BCF.APIObjects.V21
{
    public class Snapshot_POST
    {

        public Snapshot_type Snapshot_type { get; set; }

        private string _snapshot_data;
        
        public virtual string Snapshot_data
        {
            get
            {
                return _snapshot_data;
            }
            set
            {
                _snapshot_data = value;
            }
        }
    }
}
