//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;

namespace Dangl.BCF.APIObjects.V21
{
    public class Topic_event_GET
    {
        
        private Guid _topic_guid;
        
        private DateTime _date;
        
        private string _author;
        
        private List<Event_action> _actions;
        
        [Required()]
        public virtual Guid Topic_guid
        {
            get
            {
                return _topic_guid;
            }
            set
            {
                _topic_guid = value;
            }
        }
        
        [Required()]
        public virtual DateTime Date
        {
            get
            {
                return _date;
            }
            set
            {
                _date = value;
            }
        }
        
        [Required()]
        public virtual string Author
        {
            get
            {
                return _author;
            }
            set
            {
                _author = value;
            }
        }
        
        [MinLength(1)]
        public virtual List<Event_action> Actions
        {
            get
            {
                return _actions;
            }
            set
            {
                _actions = value;
            }
        }
    }
}
