//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Dangl.BCF.APIObjects.V21
{
    public class Version
    {
        
        private string _version_id;
        
        private string _detailed_version;
        
        [Required()]
        public virtual string Version_id
        {
            get
            {
                return _version_id;
            }
            set
            {
                _version_id = value;
            }
        }
        
        public virtual string Detailed_version
        {
            get
            {
                return _detailed_version;
            }
            set
            {
                _detailed_version = value;
            }
        }
    }
}
