//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dangl.BCF.APIObjects.V21
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public class Viewpoint_GET
    {
        private int _index;
        
        private Guid _guid;
        
        private Orthogonal_camera _orthogonal_camera;
        
        private Perspective_camera _perspective_camera;
        
        private List<Line> _lines;
        
        private List<Clipping_plane> _clipping_planes;
        
        private List<Bitmap_GET> _bitmaps;
        
        private Snapshot_GET _snapshot;
        
        public virtual int Index
        {
            get
            {
                return _index;
            }
            set
            {
                _index = value;
            }
        }
        
        [Required()]
        public virtual Guid Guid
        {
            get
            {
                return _guid;
            }
            set
            {
                _guid = value;
            }
        }
        
        public virtual Orthogonal_camera Orthogonal_camera
        {
            get
            {
                return _orthogonal_camera;
            }
            set
            {
                _orthogonal_camera = value;
            }
        }
        
        public virtual Perspective_camera Perspective_camera
        {
            get
            {
                return _perspective_camera;
            }
            set
            {
                _perspective_camera = value;
            }
        }
        
        public virtual List<Line> Lines
        {
            get
            {
                return _lines;
            }
            set
            {
                _lines = value;
            }
        }
        
        public virtual List<Clipping_plane> Clipping_planes
        {
            get
            {
                return _clipping_planes;
            }
            set
            {
                _clipping_planes = value;
            }
        }
        
        public virtual List<Bitmap_GET> Bitmaps
        {
            get
            {
                return _bitmaps;
            }
            set
            {
                _bitmaps = value;
            }
        }
        
        public virtual Snapshot_GET Snapshot
        {
            get
            {
                return _snapshot;
            }
            set
            {
                _snapshot = value;
            }
        }
    }
}
