using System;
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
namespace Dangl.BCF
{
    // This file is automatically generated from the build script
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class FileVersionProvider
    {
        public static string AssemblyVersion => "1.2.4.0";
        public static string FileVersion => "1.2.4";
        public static string NuGetVersion => "1.2.4-beta0006";
        public static DateTime BuildDateUtc => new DateTime(2019, 5, 7, 9, 53, 37, DateTimeKind.Utc);
    }
}
