//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iabi.BCF.Tests.BCFTestCases.v21.CreateAndExport {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BCFTestCaseData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BCFTestCaseData() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iabi.BCF.Tests.BCFTestCases.v21.CreateAndExport.BCFTestCaseData", typeof(BCFTestCaseData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die # Minimum Information
        ///
        ///This test case verifies support of a minimal BCFzip file.
        ///
        ///## Testing process
        ///
        ///1. Import _MinimumInformation.bcfzip_.
        ///2. Verify the bcfzip was imported correctly:
        ///&gt; 1. The imported topic does have the following properties:
        ///&gt;&gt; * Guid: 9898DE65-C0CE-414B-857E-1DF97FFAED8D
        ///&gt;&gt; * Title: Minimum information BCFZip topic.
        ///&gt;&gt; * CreationDate: 2015-07-15T13:12:42Z (Z indicating an UTC timestamp)
        ///&gt;&gt; * CreationAuthor: Developer@example.com
        ///3. Export the topic you imported to _exporte [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string MinimumInformation_Readme {
            get {
                return ResourceManager.GetString("MinimumInformation_Readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MinimumInformation ähnelt.
        /// </summary>
        internal static string MinimumInformation_TestCaseName {
            get {
                return ResourceManager.GetString("MinimumInformation_TestCaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 9898DE65-C0CE-414B-857E-1DF97FFAED8D ähnelt.
        /// </summary>
        internal static string MinimumInformation_TopicGuid {
            get {
                return ResourceManager.GetString("MinimumInformation_TopicGuid", resourceCulture);
            }
        }
    }
}
