//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace iabi.BCF.APIObjects.V21
{
    public class Auth_GET
    {
        
        private string _oauth2_auth_url;
        
        private string _oauth2_token_url;
        
        private string _oauth2_dynamic_client_reg_url;
        
        private bool _http_basic_supported;
        
        private List<string> _supported_oauth2_flows;
        
        public virtual string Oauth2_auth_url
        {
            get
            {
                return _oauth2_auth_url;
            }
            set
            {
                _oauth2_auth_url = value;
            }
        }
        
        public virtual string Oauth2_token_url
        {
            get
            {
                return _oauth2_token_url;
            }
            set
            {
                _oauth2_token_url = value;
            }
        }
        
        public virtual string Oauth2_dynamic_client_reg_url
        {
            get
            {
                return _oauth2_dynamic_client_reg_url;
            }
            set
            {
                _oauth2_dynamic_client_reg_url = value;
            }
        }
        
        public virtual bool Http_basic_supported
        {
            get
            {
                return _http_basic_supported;
            }
            set
            {
                _http_basic_supported = value;
            }
        }
        
        public virtual List<string> Supported_oauth2_flows
        {
            get
            {
                return _supported_oauth2_flows;
            }
            set
            {
                _supported_oauth2_flows = value;
            }
        }
    }
}
