//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generated
{
    using System;
    
    
    public class Auth_GET
    {
        
        private object _oauth2_auth_url;
        
        private object _oauth2_token_url;
        
        private object _oauth2_dynamic_client_reg_url;
        
        private object _http_basic_supported;
        
        private object _supported_oauth2_flows;
        
        public virtual object Oauth2_auth_url
        {
            get
            {
                return _oauth2_auth_url;
            }
            set
            {
                _oauth2_auth_url = value;
            }
        }
        
        public virtual object Oauth2_token_url
        {
            get
            {
                return _oauth2_token_url;
            }
            set
            {
                _oauth2_token_url = value;
            }
        }
        
        public virtual object Oauth2_dynamic_client_reg_url
        {
            get
            {
                return _oauth2_dynamic_client_reg_url;
            }
            set
            {
                _oauth2_dynamic_client_reg_url = value;
            }
        }
        
        public virtual object Http_basic_supported
        {
            get
            {
                return _http_basic_supported;
            }
            set
            {
                _http_basic_supported = value;
            }
        }
        
        public virtual object Supported_oauth2_flows
        {
            get
            {
                return _supported_oauth2_flows;
            }
            set
            {
                _supported_oauth2_flows = value;
            }
        }
    }
}
