//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generated
{
    using System;
    using System.ComponentModel.DataAnnotations;
    
    
    public class Bim_snippet
    {
        
        private string _snippet_type;
        
        private bool _is_external;
        
        private string _reference;
        
        private string _reference_schema;
        
        [Required()]
        public virtual string Snippet_type
        {
            get
            {
                return _snippet_type;
            }
            set
            {
                _snippet_type = value;
            }
        }
        
        [Required()]
        public virtual bool Is_external
        {
            get
            {
                return _is_external;
            }
            set
            {
                _is_external = value;
            }
        }
        
        [Required()]
        public virtual string Reference
        {
            get
            {
                return _reference;
            }
            set
            {
                _reference = value;
            }
        }
        
        [Required()]
        public virtual string Reference_schema
        {
            get
            {
                return _reference_schema;
            }
            set
            {
                _reference_schema = value;
            }
        }
    }
}
