//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;

namespace iabi.BCF.APIObjects.V21
{
    public class Comment_GET
    {
        
        private Guid _guid;
        
        private DateTime _date;
        
        private string _author;
        
        private string _comment;

        private Guid _topic_guid;

        private Guid? _viewpoint_guid;

        private Guid? _reply_to_comment_guid;
        
        private DateTime? _modified_date;
        
        private string _modified_author;
        
        private Comment_authorization _authorization;
        
        [Required()]
        public virtual Guid Guid
        {
            get
            {
                return _guid;
            }
            set
            {
                _guid = value;
            }
        }
        
        [Required()]
        public virtual DateTime Date
        {
            get
            {
                return _date;
            }
            set
            {
                _date = value;
            }
        }
        
        [Required()]
        public virtual string Author
        {
            get
            {
                return _author;
            }
            set
            {
                _author = value;
            }
        }
        
        [Required()]
        public virtual string Comment
        {
            get
            {
                return _comment;
            }
            set
            {
                _comment = value;
            }
        }
        
        [Required()]
        public virtual Guid Topic_guid
        {
            get
            {
                return _topic_guid;
            }
            set
            {
                _topic_guid = value;
            }
        }
        
        public virtual Guid? Viewpoint_guid
        {
            get
            {
                return _viewpoint_guid;
            }
            set
            {
                _viewpoint_guid = value;
            }
        }
        
        public virtual Guid? Reply_to_comment_guid
        {
            get
            {
                return _reply_to_comment_guid;
            }
            set
            {
                _reply_to_comment_guid = value;
            }
        }
        
        public virtual DateTime? Modified_date
        {
            get
            {
                return _modified_date;
            }
            set
            {
                _modified_date = value;
            }
        }
        
        public virtual string Modified_author
        {
            get
            {
                return _modified_author;
            }
            set
            {
                _modified_author = value;
            }
        }
        
        public virtual Comment_authorization Authorization
        {
            get
            {
                return _authorization;
            }
            set
            {
                _authorization = value;
            }
        }
    }
}
