//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generated
{
    using System;
    using generated;
    using System.ComponentModel.DataAnnotations;
    
    
    public class Comment_GET
    {
        
        private string _guid;
        
        private string _date;
        
        private string _author;
        
        private string _comment;
        
        private string _topic_guid;
        
        private object _viewpoint_guid;
        
        private object _reply_to_comment_guid;
        
        private object _modified_date;
        
        private object _modified_author;
        
        private object _authorization;
        
        [Required()]
        public virtual string Guid
        {
            get
            {
                return _guid;
            }
            set
            {
                _guid = value;
            }
        }
        
        [Required()]
        public virtual string Date
        {
            get
            {
                return _date;
            }
            set
            {
                _date = value;
            }
        }
        
        [Required()]
        public virtual string Author
        {
            get
            {
                return _author;
            }
            set
            {
                _author = value;
            }
        }
        
        [Required()]
        public virtual string Comment
        {
            get
            {
                return _comment;
            }
            set
            {
                _comment = value;
            }
        }
        
        [Required()]
        public virtual string Topic_guid
        {
            get
            {
                return _topic_guid;
            }
            set
            {
                _topic_guid = value;
            }
        }
        
        public virtual object Viewpoint_guid
        {
            get
            {
                return _viewpoint_guid;
            }
            set
            {
                _viewpoint_guid = value;
            }
        }
        
        public virtual object Reply_to_comment_guid
        {
            get
            {
                return _reply_to_comment_guid;
            }
            set
            {
                _reply_to_comment_guid = value;
            }
        }
        
        public virtual object Modified_date
        {
            get
            {
                return _modified_date;
            }
            set
            {
                _modified_date = value;
            }
        }
        
        public virtual object Modified_author
        {
            get
            {
                return _modified_author;
            }
            set
            {
                _modified_author = value;
            }
        }
        
        public virtual object Authorization
        {
            get
            {
                return _authorization;
            }
            set
            {
                _authorization = value;
            }
        }
    }
}
