//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;

namespace iabi.BCF.APIObjects.V21
{
    public class Comment_POST
    {
        
        private string _comment;

        private Guid? _viewpoint_guid;

        private Guid? _reply_to_comment_guid;
        
        [Required()]
        public virtual string Comment
        {
            get
            {
                return _comment;
            }
            set
            {
                _comment = value;
            }
        }
        
        public virtual Guid? Viewpoint_guid
        {
            get
            {
                return _viewpoint_guid;
            }
            set
            {
                _viewpoint_guid = value;
            }
        }
        
        public virtual Guid? Reply_to_comment_guid
        {
            get
            {
                return _reply_to_comment_guid;
            }
            set
            {
                _reply_to_comment_guid = value;
            }
        }
    }
}
