//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iabi.BCF.APIObjects.V21
{
    public class Component
    {
        
        private string _ifc_guid;
        
        private string _originating_system;
        
        private string _authoring_tool_id;
        
        public virtual string Ifc_guid
        {
            get
            {
                return _ifc_guid;
            }
            set
            {
                _ifc_guid = value;
            }
        }
        
        public virtual string Originating_system
        {
            get
            {
                return _originating_system;
            }
            set
            {
                _originating_system = value;
            }
        }
        
        public virtual string Authoring_tool_id
        {
            get
            {
                return _authoring_tool_id;
            }
            set
            {
                _authoring_tool_id = value;
            }
        }
    }
}
