//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generated
{
    using System;
    
    
    public class Component
    {
        
        private object _ifc_guid;
        
        private object _originating_system;
        
        private object _authoring_tool_id;
        
        public virtual object Ifc_guid
        {
            get
            {
                return _ifc_guid;
            }
            set
            {
                _ifc_guid = value;
            }
        }
        
        public virtual object Originating_system
        {
            get
            {
                return _originating_system;
            }
            set
            {
                _originating_system = value;
            }
        }
        
        public virtual object Authoring_tool_id
        {
            get
            {
                return _authoring_tool_id;
            }
            set
            {
                _authoring_tool_id = value;
            }
        }
    }
}
