//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generated
{
    using System;
    
    
    public class Document_reference_PUT
    {
        
        private object _guid;
        
        private object _referenced_document;
        
        private object _description;
        
        public virtual object Guid
        {
            get
            {
                return _guid;
            }
            set
            {
                _guid = value;
            }
        }
        
        public virtual object Referenced_document
        {
            get
            {
                return _referenced_document;
            }
            set
            {
                _referenced_document = value;
            }
        }
        
        public virtual object Description
        {
            get
            {
                return _description;
            }
            set
            {
                _description = value;
            }
        }
    }
}
