//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generated
{
    using System;
    using System.ComponentModel.DataAnnotations;
    
    
    public class Document_GET
    {
        
        private string _guid;
        
        private string _filename;
        
        [Required()]
        public virtual string Guid
        {
            get
            {
                return _guid;
            }
            set
            {
                _guid = value;
            }
        }
        
        [Required()]
        public virtual string Filename
        {
            get
            {
                return _filename;
            }
            set
            {
                _filename = value;
            }
        }
    }
}
