//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iabi.BCF.APIObjects.V21
{
    public class Document_reference_POST
    {
        
        private string _referenced_document;
        
        private string _description;
        
        public virtual string Referenced_document
        {
            get
            {
                return _referenced_document;
            }
            set
            {
                _referenced_document = value;
            }
        }
        
        public virtual string Description
        {
            get
            {
                return _description;
            }
            set
            {
                _description = value;
            }
        }
    }
}
