//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generated
{
    using System;
    
    
    // Schema for a single file GET, BCF REST API.
    public class File_GET
    {
        
        private object _ifc_project;
        
        private object _ifc_spatial_structure_element;
        
        private object _file_name;
        
        private object _date;
        
        private object _reference;
        
        public virtual object Ifc_project
        {
            get
            {
                return _ifc_project;
            }
            set
            {
                _ifc_project = value;
            }
        }
        
        public virtual object Ifc_spatial_structure_element
        {
            get
            {
                return _ifc_spatial_structure_element;
            }
            set
            {
                _ifc_spatial_structure_element = value;
            }
        }
        
        public virtual object File_name
        {
            get
            {
                return _file_name;
            }
            set
            {
                _file_name = value;
            }
        }
        
        public virtual object Date
        {
            get
            {
                return _date;
            }
            set
            {
                _date = value;
            }
        }
        
        public virtual object Reference
        {
            get
            {
                return _reference;
            }
            set
            {
                _reference = value;
            }
        }
    }
}
