//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iabi.BCF.APIObjects.V21
{
    public class Point
    {
        
        private float _x;
        
        private float _y;
        
        private float _z;
        
        public virtual float X
        {
            get
            {
                return _x;
            }
            set
            {
                _x = value;
            }
        }
        
        public virtual float Y
        {
            get
            {
                return _y;
            }
            set
            {
                _y = value;
            }
        }
        
        public virtual float Z
        {
            get
            {
                return _z;
            }
            set
            {
                _z = value;
            }
        }
    }
}
