//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;

namespace iabi.BCF.APIObjects.V21
{
    // Schema for single related topic GET, BCF REST API.
    public class Related_topic_GET
    {
        
        private Guid _related_topic_guid;
        
        [Required()]
        public virtual Guid Related_topic_guid
        {
            get
            {
                return _related_topic_guid;
            }
            set
            {
                _related_topic_guid = value;
            }
        }
    }
}
