//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generated
{
    using System;
    using generated;
    
    
    // Schema for selection GET, BCF REST API.
    public class Selection_GET
    {
        
        private ComponentList _selection;
        
        public virtual ComponentList Selection
        {
            get
            {
                return _selection;
            }
            set
            {
                _selection = value;
            }
        }
    }
}
