//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generated
{
    using System;
    using generated;
    
    
    public class Viewpoint_POST
    {
        
        private object _index;
        
        private Orthogonal_camera _orthogonal_camera;
        
        private Perspective_camera _perspective_camera;
        
        private object _lines;
        
        private object _clipping_planes;
        
        private object _bitmaps;
        
        private Snapshot_POST _snapshot;
        
        private Components _components;
        
        public virtual object Index
        {
            get
            {
                return _index;
            }
            set
            {
                _index = value;
            }
        }
        
        public virtual Orthogonal_camera Orthogonal_camera
        {
            get
            {
                return _orthogonal_camera;
            }
            set
            {
                _orthogonal_camera = value;
            }
        }
        
        public virtual Perspective_camera Perspective_camera
        {
            get
            {
                return _perspective_camera;
            }
            set
            {
                _perspective_camera = value;
            }
        }
        
        public virtual object Lines
        {
            get
            {
                return _lines;
            }
            set
            {
                _lines = value;
            }
        }
        
        public virtual object Clipping_planes
        {
            get
            {
                return _clipping_planes;
            }
            set
            {
                _clipping_planes = value;
            }
        }
        
        public virtual object Bitmaps
        {
            get
            {
                return _bitmaps;
            }
            set
            {
                _bitmaps = value;
            }
        }
        
        public virtual Snapshot_POST Snapshot
        {
            get
            {
                return _snapshot;
            }
            set
            {
                _snapshot = value;
            }
        }
        
        public virtual Components Components
        {
            get
            {
                return _components;
            }
            set
            {
                _components = value;
            }
        }
    }
}
