//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iabi.BCF.APIObjects.V21
{
    using System;
    using System.Collections.Generic;


    public class Viewpoint_POST
    {
        
        private int _index;
        
        private Orthogonal_camera _orthogonal_camera;
        
        private Perspective_camera _perspective_camera;
        
        private List<Line> _lines;
        
        private List<Clipping_plane> _clipping_planes;
        
        private List<Bitmap_POST> _bitmaps;
        
        private Snapshot_POST _snapshot;
        
        private Components _components;
        
        public virtual int Index
        {
            get
            {
                return _index;
            }
            set
            {
                _index = value;
            }
        }
        
        public virtual Orthogonal_camera Orthogonal_camera
        {
            get
            {
                return _orthogonal_camera;
            }
            set
            {
                _orthogonal_camera = value;
            }
        }
        
        public virtual Perspective_camera Perspective_camera
        {
            get
            {
                return _perspective_camera;
            }
            set
            {
                _perspective_camera = value;
            }
        }
        
        public virtual List<Line> Lines
        {
            get
            {
                return _lines;
            }
            set
            {
                _lines = value;
            }
        }
        
        public virtual List<Clipping_plane> Clipping_planes
        {
            get
            {
                return _clipping_planes;
            }
            set
            {
                _clipping_planes = value;
            }
        }
        
        public virtual List<Bitmap_POST> Bitmaps
        {
            get
            {
                return _bitmaps;
            }
            set
            {
                _bitmaps = value;
            }
        }
        
        public virtual Snapshot_POST Snapshot
        {
            get
            {
                return _snapshot;
            }
            set
            {
                _snapshot = value;
            }
        }
        
        public virtual Components Components
        {
            get
            {
                return _components;
            }
            set
            {
                _components = value;
            }
        }
    }
}
